version: "2.4"

services:

  server:
    image: aemdesign/java-buildpack:jdk11-ubuntu
    restart: always
    extends:
      file: ../common/config-tz.yml
      service: config
    working_dir: /content
    hostname: "server"
    command: "bash -c -l /build/source/docker-serve.sh"
    labels:
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.gvfn.rule: "Host(`gvfn.localhost`)"
      traefik.http.routers.gvfn.entrypoints: web
      traefik.http.routers.gvfn_https.rule: "Host(`gvfn.localhost`)"
      traefik.http.routers.gvfn_https.tls: true
      traefik.http.routers.gvfn_https.entrypoints: websecure
      traefik.http.services.gvfn.loadbalancer.passHostHeader: true
      traefik.http.services.gvfn.loadbalancer.server.port: 4000
    environment:
      - LANG=en_US.UTF-8
      - PORT=4000
      - PORT_LIVERELOAD=35129
    volumes:
      - ../../:/build/source
    networks:
      - internal

  webp-create:
    image: aemdesign/java-buildpack:jdk11
    extends:
      file: ../common/config-tz.yml
      service: config
    working_dir: /content
    hostname: "webp-create"
    command: "bash -c -l /build/source/docker-webp.sh"
    environment:
      - LANG=en_US.UTF-8
      - MODE=CREATE
    volumes:
      - ../../:/build/source
    profiles:
      - webp
    networks:
      - internal

  webp-update:
    image: aemdesign/java-buildpack:jdk11
    extends:
      file: ../common/config-tz.yml
      service: config
    working_dir: /content
    hostname: "webp-update"
    command: "bash -c -l /build/source/docker-webp.sh"
    environment:
      - LANG=en_US.UTF-8
      - MODE=UPDATE
    volumes:
      - ../../:/build/source
    profiles:
      - webp
    networks:
      - internal

networks:
  internal:

volumes:
  data:
