import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'KnowledgeFund',
      link: {type: 'doc', id: 'knowledgefund/overview'},
      items: [
        'knowledgefund/overview',
        'knowledgefund/model',
        {
          type: 'category',
          label: 'Knowledge Ontology',
          link: {type: 'doc', id: 'gxp/overview'},
          items: [
            'gxp/model-overview',
            'gxp/model-layers',
            'gxp/model-collaboration',
            'gxp/model-business',
            'gxp/model-service',
            'gxp/model-application',
            'gxp/model-deployment',
            'gxp/model-data',
            'gxp/model-infrastructure',
            'gxp/tech-architecture',
            {
              type: 'category',
              label: 'Diagrams',
              items: [
                'gxp/overview-diagram',
                'gxp/terms',
                'gxp/measurement',
                'gxp/questions',
                'gxp/viewpoints',
              ],
            },
          ],
        },
        'knowledgefund/diagram',
        'knowledgefund/bootstrap',
        'knowledgefund/consulting',
        'knowledgefund/ontology-architecture',
        'knowledgefund/ontology-principles',
        'knowledgefund/ontouml-guide',
        'knowledgefund/frameworks-as-views',
        'knowledgefund/knowledge-fog',
        'knowledgefund/agent-discovery',
        'knowledgefund/experiences',
      ],
    },
    {
      type: 'category',
      label: 'Governance',
      link: {type: 'doc', id: 'governance/overview'},
      items: [
        'governance/overview',
        'governance/introduction',
        'governance/governance-origin',
        'governance/governance-paradigm',
        'governance/governance-evolution',
        'governance/perspectives',
        'governance/governance-global',
        'governance/governance-modern',
        'governance/governance-corporate',
        'governance/governance-enterprise',
        'governance/governance-it',
        'governance/governance-systemic',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      link: {type: 'doc', id: 'frameworks/overview'},
      items: [
        'frameworks/overview',
        'frameworks/architectural-thinking',
        'frameworks/pragmaticea',
        'frameworks/avancier-methods',
        'frameworks/panorama360',
        'frameworks/trak',
        'frameworks/modaf',
        'frameworks/dodaf',
        'frameworks/ripose-casper',
        'frameworks/archimate',
        'frameworks/uaf',
        'frameworks/updm',
        'frameworks/ufo',
        'frameworks/ontouml',
        'frameworks/sean',
      ],
    },
    {
      type: 'category',
      label: 'Brand',
      link: {type: 'doc', id: 'brand/brand-guidelines'},
      items: ['brand/brand-guidelines'],
    },
  ],
};

export default sidebars;
