title: Governance Foundation
name: Governance Foundation
email: devops@governance.foundation
description: > # this means to ignore newlines until next attribute
  Governance Foundation exploring foundations for governance
github_username:  governance-foundation
